version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US
  revive:
    enable-all-rules: false
    rules:
      - name: unused-parameter
        disabled: false

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: server/configuration.go
      linters:
        - unused
    - path: _test\.go
      linters:
        - bodyclose
        - scopelint # https://github.com/kyoh86/scopelint/issues/4
    - linters:
        - revive
      text: unused-parameter
    - linters:
        - revive
      text: exported
    - linters:
        - revive
      text: package-comments
