template: testify
all: false
formatter: "goimports"
dir: "{{.InterfaceDirRelative}}"
pkgname: "{{.SrcPackageName}}"
# template-data:
#   boilerplate-file: "./.mockery.license.header"
packages:
  github.com/mattermost/mattermost-plugin-msteams-devsecops/server/msteams:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "client_mock.go"
      structname: "{{.Mock}}{{.InterfaceName}}"
    interfaces:
      Client:
  github.com/mattermost/mattermost-plugin-msteams-devsecops/server/store/pluginstore:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "store_mock.go"
      structname: "{{.Mock}}{{.InterfaceName}}"
    interfaces:
      Store:
